name: Run Selenium Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome
          - firefox
          - edge

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: gradle:jdk21-graal

    services:
      selenium:
        image: selenium/standalone-${{ github.event.inputs.browser }}:latest
        ports:
          - 4444:4444
          - 7900:7900
        options: --shm-size=2gb

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download element selectors
      uses: actions/download-artifact@v4
      with:
        name: element-selectors
        path: src/test/resources/

    - name: Run build including the test
      env:
        OPENROUTER_API_KEY: ${{ vars.OPENROUTER_API_KEY }}
      run: gradle build --info

    - name: Upload element selectors
      uses: actions/upload-artifact@v4
      with:
        name: element-selectors
        path: src/test/resources/elementSelectors.properties
        retention-days: 7
