name: Run Selenium Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome
          - firefox
          - edge

jobs:
  download-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Download element selectors
      continue-on-error: true
      uses: actions/download-artifact@v4
      with:
        name: element-selectors
        path: src/test/resources/
    - name: Verify downloaded artifact
      continue-on-error: true
      run: |
        ls -l src/test/resources/
        cat src/test/resources/elementSelectors.properties || echo "File not found"

  test:
    runs-on: ubuntu-latest
    needs: download-artifacts
    services:
      selenium:
        image: selenium/standalone-${{ github.event.inputs.browser }}:latest
        ports:
          - 4444:4444
          - 7900:7900
        options: --shm-size=2gb

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-java@v4
      with:
        distribution: 'graalvm'
        java-version: '21'
    
    - name: Run build including the test
      env:
        LLM_PROVIDER_API_KEY: ${{ secrets.LLM_PROVIDER_API_KEY }}
        LLM_BASE_API: ${{ vars.LLM_BASE_API }}
        LLM_MODEL: ${{ vars.LLM_MODEL }}
      run: ./gradlew build --info

    - name: Upload element selectors
      uses: actions/upload-artifact@v4
      with:
        name: element-selectors
        path: src/test/resources/elementSelectors.properties
        retention-days: 7
