name: Run Selenium Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Which browser to test
        required: true
        options:
          - chrome
          - firefox
          - edge

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: gradle:jdk21-graal

    services:
      selenium:
        image: selenium/standalone-${{ github.event.inputs.browser }}:latest
        ports:
          - 4444:4444
          - 7900:7900
        options: --shm-size=2gb

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run build including the test
      run: gradle build --info
